import { useCallback, useEffect, useState } from 'react';
import { Megaphone, Plus, Eye, XCircle, Send } from 'lucide-react';
import { api } from '../../api/client.js';
import { useLanguage } from '../../contexts/LanguageContext.jsx';
import { useToast } from '../../contexts/ToastContext.jsx';
import Button from '../../components/ui/Button.jsx';
import Input from '../../components/ui/Input.jsx';
import BottomSheet from '../../components/ui/BottomSheet.jsx';

const empty = { name:'', subject:'', bn:'', en:'', audience:'subscribers', scheduledAt:'' };

export default function Campaigns() {
  const { t, lang } = useLanguage(); const toast = useToast();
  const [items,setItems]=useState(null), [editing,setEditing]=useState(false), [form,setForm]=useState(empty), [busy,setBusy]=useState(false);
  const load=useCallback(async()=>{try{const r=await api.get('/admin/campaigns',{limit:50});setItems(r.data.campaigns||[]);}catch(e){toast.error(e.message);}},[toast]);
  useEffect(()=>{load();},[load]);
  const set=(k,v)=>setForm(f=>({...f,[k]:v}));
  const save=async(e)=>{e.preventDefault();setBusy(true);try{await api.post('/admin/campaigns',{name:form.name,subject:form.subject,content:{bn:form.bn||undefined,en:form.en||undefined},audience:form.audience,scheduledAt:form.scheduledAt||undefined});toast.success(t('admin.campaigns.created'));setEditing(false);setForm(empty);load();}catch(e){toast.error(e.message);}finally{setBusy(false);}};
  const preview=async(c)=>{try{const r=await api.post(`/admin/campaigns/${c._id}/preview`);toast.success(`${t('admin.campaigns.recipients')}: ${r.data.recipientCount}`);load();}catch(e){toast.error(e.message);}};
  const cancel=async(c)=>{try{await api.post(`/admin/campaigns/${c._id}/cancel`);toast.success(t('admin.campaigns.cancelled'));load();}catch(e){toast.error(e.message);}};
  const send=async(c)=>{if(!window.confirm(t('admin.campaigns.sendConfirm')))return;try{const r=await api.post(`/admin/campaigns/${c._id}/send`,{confirm:true});toast.success(r.data.campaign?.failedCount?t('admin.campaigns.partial'):t('admin.campaigns.sent'));load();}catch(e){toast.error(e.message||t('admin.campaigns.sendFailed'));}};
  const labelAudience=(a)=>t(`admin.campaigns.audience_${a}`);
  return <div className="flex flex-col gap-4">
    <div className="flex items-center justify-between gap-3"><div><p className="text-sm text-muted">{t('admin.campaigns.foundation')}</p></div><Button onClick={()=>setEditing(true)}><Plus size={18}/>{t('admin.campaigns.add')}</Button></div>
    {!items?<div className="h-32 animate-pulse rounded-card bg-surface-2"/>:items.length===0?<div className="rounded-card border border-dashed border-line p-10 text-center"><Megaphone className="mx-auto text-accent" size={32}/><p className="mt-3 font-semibold">{t('admin.campaigns.empty')}</p></div>:<div className="grid gap-3 lg:grid-cols-2">{items.map(c=><article key={c._id} className="rounded-card border border-line bg-surface p-4"><div className="flex items-start justify-between gap-3"><div><h2 className="font-bold">{c.name}</h2><p className="mt-1 text-sm text-muted">{c.subject}</p></div><span className="rounded-full bg-surface-2 px-2.5 py-1 text-xs font-semibold">{t(`admin.campaigns.status_${c.status}`)}</span></div><div className="mt-4 grid grid-cols-2 gap-3 text-sm"><div><span className="text-muted">{t('admin.campaigns.audience')}</span><p className="font-semibold">{labelAudience(c.audience)}</p></div><div><span className="text-muted">{t('admin.campaigns.recipients')}</span><p className="font-semibold">{c.recipientCount}</p></div><div><span className="text-muted">{t('admin.campaigns.scheduled')}</span><p className="font-semibold">{c.scheduledAt?new Date(c.scheduledAt).toLocaleString():t('admin.campaigns.notScheduled')}</p></div><div><span className="text-muted">{t('admin.campaigns.provider')}</span><p className="font-semibold">{t('admin.campaigns.providerDisabled')}</p></div></div><div className="mt-4 flex flex-wrap gap-2"><Button variant="outline" onClick={()=>preview(c)}><Eye size={16}/>{t('admin.campaigns.preview')}</Button>{['draft','scheduled'].includes(c.status)&&<Button onClick={()=>send(c)}><Send size={16}/>{t('admin.campaigns.send')}</Button>}{c.status!=='cancelled'&&!['sent','sending'].includes(c.status)&&<Button variant="ghost" className="text-danger" onClick={()=>cancel(c)}><XCircle size={16}/>{t('admin.campaigns.cancel')}</Button>}</div></article>)}</div>}
    <BottomSheet open={editing} onClose={()=>setEditing(false)} title={t('admin.campaigns.newTitle')}><form onSubmit={save} className="flex flex-col gap-4 p-4"><Input label={t('admin.campaigns.name')} value={form.name} onChange={e=>set('name',e.target.value)} required/><Input label={t('admin.campaigns.subject')} value={form.subject} onChange={e=>set('subject',e.target.value)} required/><label className="flex flex-col gap-1.5 text-sm font-medium">{t('admin.campaigns.audience')}<select value={form.audience} onChange={e=>set('audience',e.target.value)} className="min-h-12 rounded-control border border-line bg-surface px-4"><option value="subscribers">{labelAudience('subscribers')}</option><option value="consented_customers">{labelAudience('consented_customers')}</option><option value="all_marketing">{labelAudience('all_marketing')}</option></select></label><Input label={t('admin.campaigns.bn')} value={form.bn} onChange={e=>set('bn',e.target.value)}/><Input label={t('admin.campaigns.en')} value={form.en} onChange={e=>set('en',e.target.value)}/><Input label={t('admin.campaigns.scheduled')} type="datetime-local" value={form.scheduledAt} onChange={e=>set('scheduledAt',e.target.value)} hint={t('admin.campaigns.scheduleHint')}/><p className="rounded-control bg-warning/10 p-3 text-sm text-warning">{t('admin.campaigns.noSendWarning')}</p><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={()=>setEditing(false)}>{t('admin.campaigns.cancel')}</Button><Button type="submit" disabled={busy}>{busy?t('admin.common.loading'):t('admin.campaigns.save')}</Button></div></form></BottomSheet>
  </div>;
}
