import { useCallback, useEffect, useMemo, useState } from 'react';
import { Megaphone, Pencil, Plus, Trash2, Tag, Power } from 'lucide-react';
import { api } from '../../api/client.js';
import { useLanguage } from '../../contexts/LanguageContext.jsx';
import { useToast } from '../../components/ui/Toast.jsx';
import Button from '../../components/ui/Button.jsx';
import Input from '../../components/ui/Input.jsx';
import BottomSheet from '../../components/ui/BottomSheet.jsx';
import ConfirmSheet from '../../components/ui/ConfirmSheet.jsx';

const empty = { code:'', descBn:'', descEn:'', type:'percent', value:'', maxDiscount:'', minOrder:'', startsAt:'', expiresAt:'', usageLimit:'', isActive:true, products:[], categories:[] };
const money = (n) => `৳${Number(n || 0).toLocaleString('en-BD')}`;
const localName = (x, lang) => x?.name?.[lang] || x?.name?.bn || x?.name?.en || '—';

export default function Marketing() {
  const { t, lang } = useLanguage();
  const toast = useToast();
  const [coupons,setCoupons]=useState(null); const [products,setProducts]=useState([]); const [categories,setCategories]=useState([]);
  const [editing,setEditing]=useState(null); const [form,setForm]=useState(empty); const [busy,setBusy]=useState(false); const [del,setDel]=useState(null); const [q,setQ]=useState('');

  const load = useCallback(async () => { try { const r=await api.get('/admin/coupons',{params:{q:q||undefined,limit:50}}); setCoupons(r.data.coupons); } catch(e){toast.error(e.message);} },[q,toast]);
  const loadOptions = useCallback(async () => { try { const [p,c]=await Promise.all([api.get('/admin/products',{params:{limit:50}}),api.get('/admin/categories')]); setProducts(p.data.products||[]); setCategories(c.data.categories||[]); } catch(e){toast.error(e.message);} },[toast]);
  useEffect(()=>{load();},[load]); useEffect(()=>{loadOptions();},[loadOptions]);
  const set=(k,v)=>setForm(f=>({...f,[k]:v}));
  const openNew=()=>{setForm(empty);setEditing('new');};
  const openEdit=(c)=>setForm({code:c.code||'',descBn:c.description?.bn||'',descEn:c.description?.en||'',type:c.type,value:String(c.value??''),maxDiscount:c.maxDiscount==null?'':String(c.maxDiscount),minOrder:String(c.minOrder??''),startsAt:c.startsAt?new Date(c.startsAt).toISOString().slice(0,16):'',expiresAt:c.expiresAt?new Date(c.expiresAt).toISOString().slice(0,16):'',usageLimit:c.usageLimit==null?'':String(c.usageLimit),isActive:c.isActive!==false,products:(c.products||[]).map(x=>String(x._id||x)),categories:(c.categories||[]).map(x=>String(x._id||x))});
  const close=()=>setEditing(null);
  const toggleId=(key,id)=>set(key,form[key].includes(id)?form[key].filter(x=>x!==id):[...form[key],id]);
  const submit=async(e)=>{e.preventDefault();setBusy(true);try{const body={code:form.code,description:{bn:form.descBn||undefined,en:form.descEn||undefined},type:form.type,value:Number(form.value),maxDiscount:form.maxDiscount===''?undefined:Number(form.maxDiscount),minOrder:Number(form.minOrder||0),startsAt:form.startsAt||undefined,expiresAt:form.expiresAt||undefined,usageLimit:form.usageLimit===''?null:Number(form.usageLimit),isActive:form.isActive,products:form.products,categories:form.categories}; if(editing==='new') await api.post('/admin/coupons',body);else await api.patch(`/admin/coupons/${editing._id}`,body);toast.success(t(editing==='new'?'admin.marketing.created':'admin.marketing.updated'));close();load();}catch(e){toast.error(e.message);}finally{setBusy(false);}};
  const remove=async()=>{setBusy(true);try{await api.delete(`/admin/coupons/${del._id}`);toast.success(t('admin.marketing.deleted'));setDel(null);load();}catch(e){toast.error(e.message);}finally{setBusy(false);}};
  const toggle=async(c)=>{try{await api.patch(`/admin/coupons/${c._id}`,{isActive:!c.isActive});load();}catch(e){toast.error(e.message);}};
  const selectedProducts=useMemo(()=>products.filter(p=>form.products.includes(String(p._id))),[products,form.products]);
  return <div className="flex flex-col gap-4">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-end"><div className="flex-1"><Input label={t('admin.marketing.search')} value={q} onChange={e=>setQ(e.target.value)} placeholder={t('admin.marketing.searchPlaceholder')}/></div><Button onClick={openNew}><Plus size={18}/>{t('admin.marketing.add')}</Button></div>
    {!coupons?<div className="space-y-3">{[1,2,3].map(i=><div key={i} className="h-28 animate-pulse rounded-card bg-surface-2"/>)}</div>:coupons.length===0?<div className="rounded-card border border-dashed border-line p-10 text-center"><Megaphone className="mx-auto text-accent" size={32}/><p className="mt-3 font-semibold">{t('admin.marketing.emptyTitle')}</p><p className="mt-1 text-muted">{t('admin.marketing.emptyText')}</p></div>:<div className="grid gap-3 lg:grid-cols-2">{coupons.map(c=><article key={c._id} className="rounded-card border border-line bg-surface p-4"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2"><Tag size={18} className="text-accent"/><h2 className="font-bold tracking-wide">{c.code}</h2></div><p className="mt-1 text-sm text-muted">{c.description?.[lang]||c.description?.bn||c.description?.en||t('admin.marketing.noDescription')}</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${c.isActive?'bg-success/15 text-success':'bg-muted/15 text-muted'}`}>{c.isActive?t('admin.marketing.active'):t('admin.marketing.inactive')}</span></div><div className="mt-4 grid grid-cols-2 gap-2 text-sm"><div><span className="text-muted">{t('admin.marketing.discount')}</span><p className="font-semibold">{c.type==='percent'?`${c.value}%`:`${money(c.value)}`}</p></div><div><span className="text-muted">{t('admin.marketing.used')}</span><p className="font-semibold">{c.usedCount}{c.usageLimit!=null?` / ${c.usageLimit}`:''}</p></div><div><span className="text-muted">{t('admin.marketing.minOrder')}</span><p className="font-semibold">{money(c.minOrder)}</p></div><div><span className="text-muted">{t('admin.marketing.scope')}</span><p className="font-semibold">{c.products?.length||c.categories?.length?t('admin.marketing.limited'):t('admin.marketing.allProducts')}</p></div></div><div className="mt-4 flex flex-wrap gap-2"><Button variant="outline" onClick={()=>{setEditing(c);openEdit(c);}}><Pencil size={16}/>{t('admin.marketing.edit')}</Button><Button variant="ghost" onClick={()=>toggle(c)}><Power size={16}/>{c.isActive?t('admin.marketing.disable'):t('admin.marketing.enable')}</Button><Button variant="ghost" className="text-danger" onClick={()=>setDel(c)}><Trash2 size={16}/>{t('admin.marketing.delete')}</Button></div></article>)}</div>}

    <BottomSheet open={!!editing} onClose={close} title={t(editing==='new'?'admin.marketing.newTitle':'admin.marketing.editTitle')}>
      <form onSubmit={submit} className="flex flex-col gap-4 p-4">
        <div className="grid gap-4 sm:grid-cols-2"><Input label={t('admin.marketing.code')} value={form.code} onChange={e=>set('code',e.target.value.toUpperCase())} required disabled={editing!=='new'}/><label className="flex flex-col gap-1.5 text-sm font-medium">{t('admin.marketing.type')}<select value={form.type} onChange={e=>set('type',e.target.value)} className="min-h-12 rounded-control border border-line bg-surface px-4"><option value="percent">%</option><option value="fixed">৳</option></select></label><Input label={t('admin.marketing.value')} type="number" min="0" value={form.value} onChange={e=>set('value',e.target.value)} required/><Input label={t('admin.marketing.maxDiscount')} type="number" min="0" value={form.maxDiscount} onChange={e=>set('maxDiscount',e.target.value)} hint={t('admin.marketing.maxDiscountHint')}/><Input label={t('admin.marketing.minOrder')} type="number" min="0" value={form.minOrder} onChange={e=>set('minOrder',e.target.value)}/><Input label={t('admin.marketing.usageLimit')} type="number" min="1" value={form.usageLimit} onChange={e=>set('usageLimit',e.target.value)} placeholder={t('admin.marketing.unlimited')}/><Input label={t('admin.marketing.startsAt')} type="datetime-local" value={form.startsAt} onChange={e=>set('startsAt',e.target.value)}/><Input label={t('admin.marketing.expiresAt')} type="datetime-local" value={form.expiresAt} onChange={e=>set('expiresAt',e.target.value)}/></div>
        <Input label={t('admin.marketing.descBn')} value={form.descBn} onChange={e=>set('descBn',e.target.value)}/><Input label={t('admin.marketing.descEn')} value={form.descEn} onChange={e=>set('descEn',e.target.value)}/>
        <div><p className="mb-2 text-sm font-medium">{t('admin.marketing.categories')}</p><div className="grid max-h-40 gap-2 overflow-auto rounded-control border border-line p-3 sm:grid-cols-2">{categories.map(c=><label key={c._id} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.categories.includes(String(c._id))} onChange={()=>toggleId('categories',String(c._id))}/>{localName(c,lang)}</label>)}</div></div>
        <div><p className="mb-2 text-sm font-medium">{t('admin.marketing.products')}</p><div className="grid max-h-48 gap-2 overflow-auto rounded-control border border-line p-3">{products.map(p=><label key={p._id} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.products.includes(String(p._id))} onChange={()=>toggleId('products',String(p._id))}/>{localName(p,lang)}{p.sku&&<span className="text-muted">({p.sku})</span>}</label>)}</div>{selectedProducts.length===0&&form.products.length>0&&<p className="mt-1 text-xs text-warning">{t('admin.marketing.selectedOutsideList')}</p>}</div>
        <label className="flex items-center gap-2 text-sm font-medium"><input type="checkbox" checked={form.isActive} onChange={e=>set('isActive',e.target.checked)}/>{t('admin.marketing.active')}</label>
        <div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={close}>{t('admin.marketing.cancel')}</Button><Button type="submit" disabled={busy}>{busy?t('admin.common.loading'):t('admin.marketing.save')}</Button></div>
      </form>
    </BottomSheet>
    <ConfirmSheet open={!!del} onClose={()=>setDel(null)} onConfirm={remove} busy={busy} danger title={t('admin.marketing.deleteTitle')} text={del?.code||''} confirmLabel={t('admin.marketing.delete')} cancelLabel={t('admin.admins.cancel')} closeLabel={t('admin.common.close')}/>
  </div>;
}
